name: Update README with Random Quote

on:
  schedule:
    - cron: '55 10 * * *'  # Schedule the action to run daily

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Run Docker Image
        run: |
          docker build -t update-readme .
          docker run -v $(pwd):/app update-readme
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config user.name "Yousef Sameh"
          git config user.email "yousefsameh24@gmail.com"
          git add README.md
          git commit -m "Update README with a random quote"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
