name: Update README with Random Quote

on:
  schedule:
    - cron: '5 9 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          docker build -t update-readme .
          docker run update-readme
